obstacle_range: 30.0
raytrace_range: 30.0

#footprint: [[4.4, -1], [0.0, -1], [0.0, 1], [4.4, 1]]
#footprint: [[0, -1], [-4.4, -1], [-4.4, 1], [0, 1]]
footprint: [[2.2, -1], [-2.2, -1], [-2.2, 1], [2.2, 1]]
# footprint: [[3.55, -1.0], [-0.85, -1.0], [-0.85, 1.0], [3.55, 1.0]]
footprint_padding: 0.2
transform_tolerance: 2.0

# === Static Layer ===
static_layer:
  enabled: true
  map_topic: "/perception/octomap/projected_map"
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  first_map_only: false
  subscribe_to_updates: true
  track_unknown_space: true
  trinary_costmap: true

# === Obstacle Layer with Voxel Support ===
obstacle_layer:
  enabled: true
  observation_sources: depth_points

  depth_points:
    data_type: PointCloud2
    topic: /perception/pcl/points
    marking: true
    clearing: true
    min_obstacle_height: -0.71
    max_obstacle_height: 1.3

    # voxel-specific params
    track_unknown_space: false
    expected_update_rate: 2.0
    origin_z: 0.0
    z_resolution: 0.3
    z_voxels: 10
    unknown_threshold: 15
    mark_threshold: 2

    obstacle_keep_time: 1.5
    max_obstacle_age: 2.0
    combination_method: 2 # Overwrite mode
    decay_enabled: true
    decay_model: exponential
    decay_factor: 0.75

# === Inflation Layer ===
inflation_layer:
  enabled: true
  inflation_radius: 0.6
  cost_scaling_factor: 10
