global_costmap:
  global_frame: odom
  robot_base_frame: OurCar/Center
  update_frequency: 2
  publish_frequency: 2
  rolling_window: false
  always_send_full_costmap: false
  resolution: 1.0

  plugins:
    - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: obstacle_layer, type: "costmap_2d::VoxelLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
