local_costmap:
  global_frame: odom
  robot_base_frame: OurCar/Center
  update_frequency: 5
  publish_frequency: 2
  rolling_window: true
  width: 30.0
  height: 30.0
  resolution: 0.5

  # === Inflation Layer ===
  inflation_layer:
    enabled: true
    inflation_radius: 0.5
    cost_scaling_factor: 1.8

  plugins:
    # - { name: static_layer, type: "costmap_2d::StaticLayer" }
    - { name: obstacle_layer, type: "costmap_2d::VoxelLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
